/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package coze

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/coze-dev/coze-studio/backend/api/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _breakmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _agentrunMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clearconversationhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clearconversationctxMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletemessageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmessagelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftbotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftbotcreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedraftbotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _duplicatedraftbotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdraftbotdisplayinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdraftbothistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishdraftbotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedraftbotdisplayinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _connectorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishconnectorlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _intelligence_apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdraftintelligenceinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdraftintelligencelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserrecentlyeditintelligenceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _knowledgeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdatasetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedatasetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _datasetdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdatasetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedatasetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _documentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resegmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _progressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdocumentprogressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _photoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatephotocaptionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _photodetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listphotoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sliceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createsliceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletesliceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsliceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesliceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _table_schemaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettableschemaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _validatetableschemaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _memoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdocumenttableinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsysvariableconfMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _databaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adddatabaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _binddatabaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedatabaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdatabasebyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getonlinedatabaseidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdatabasetemplateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdatabaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdatabaserecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unbinddatabaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedatabaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedatabaserecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tableMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetbottableMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectMw() []app.HandlerFunc {
	return nil
}

func _variableMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprojectvariablelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprojectvariableMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _variable0Mw() []app.HandlerFunc {
	return nil
}

func _delprofilememoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getplaygroundmemoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmemoryvariablemetaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setkvmemoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _permission_apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _patMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createpersonalaccesstokenandpermissionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletepersonalaccesstokenandpermissionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpersonalaccesstokenandpermissionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listpersonalaccesstokensMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _playground_apiMw() []app.HandlerFunc {
	return nil
}

func _deletepromptresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getofficialpromptresourcelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpromptresourceinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _upsertpromptresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftbot0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdraftbotinfoagwMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedraftbotinfoagwMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _plugin_apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkandlockplugineditMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delpluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbotdefaultparamsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getoauthschemaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getoauthstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getplaygroundpluginlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpluginapisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getplugininfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getupdatedapisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserauthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _libraryresourcelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectresourcelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishpluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerpluginmetaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resourcecopycancelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resourcecopydetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resourcecopydispatchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resourcecopyretryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebotdefaultparamsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepluginmetaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflow_apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getapidetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchdeleteworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcanvasinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _copyworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _copywktemplateapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdeletestrategyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnodeexecutehistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowprocessMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettracesdkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listpublishworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listrootspansMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getllmnodefcsettingdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getllmnodefcsettingsmergedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflownodedebugv2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nodepanelsearchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nodetemplatelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryworkflownodetypesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreleasedworkflowsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _saveworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signimageurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflowtestresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflowtestrunMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateworkflowmetaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _validatetreeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowdetailinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowreferencesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chat_flow_roleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createchatflowroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletechatflowroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getchatflowroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _project_conversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createprojectconversationdefMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteprojectconversationdefMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listprojectconversationdefMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprojectconversationdefMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _debugapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _spaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getspacelistv2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userupdateprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _accountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _infoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passportaccountinfov2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _webMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _emailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passportwebemailloginpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passwordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passportwebemailpasswordresetgetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v20Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passportwebemailregisterv2postMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passportweblogoutgetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _web0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _upload_avatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userupdateavatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconnectornameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createconversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getapimessagelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listconversationsapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversation_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clearconversationapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v3Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatv3Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepersonalaccesstokenandpermissionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _developerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _geticonMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmodeconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _botMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _reviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _playgroundMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _createdocumentreviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _mgetdocumentreviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuploadauthtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unlockplugineditMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getimagexshorturlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mgetuserbasicinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _uploadfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpluginnextversionMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _savedocumentreviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbotdatabaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _operateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbotpopupinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebotpopupinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _marketplaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkdraftbotcommitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publicgetproductlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publicgetproductdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getonboardingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedatabasebotswitchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _table_schema0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettableschema0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdatabasetableschemaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _table_fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _databasefileprogressdataMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitdatabaseinserttaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _validatedatabasetableschemaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserprofilecheckMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerpluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _upload0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowuploadauthtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversation0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draft_projectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftprojectcreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftprojectdeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftprojectupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publicfavoriteproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapigetworkflowrunhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapirunflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapistreamresumeflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapistreamrunflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflowsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapichatflowrunMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapigetworkflowinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettypelistMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _iconMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _geticon0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _geticonfordatasetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createshortcutcommandMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createupdateshortcutcommandMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publish0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkprojectversionnumberMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprojectpublishedconnectorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishprojectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpublishrecordlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reportuserbehaviorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdevpluginlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectpublishconnectorlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpublishrecorddetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoriteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publicgetuserfavoritelistv2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _extractphotocaptionMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _publicduplicateproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfileurlsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _convert2openapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getoauthschemaapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchcreateapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _revokeauthtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethistoryschemaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _filesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadfileopenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftprojectinnertasklistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftprojectcopyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getexampleworkflowlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bot0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbotonlineinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauthauthorizationcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getqueriedoauthpluginlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applyimageactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commonuploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applyimagexactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applyimagexaction0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applyuploadactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applyuploadaction0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commonMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _upload1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversation1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapicreateconversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _coze_web_appMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _impersonatecozeuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _botsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _opengetbotinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteconversationapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateconversationapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversations0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelchatapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getonlineappdataMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _search0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
func _adminMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.AdminAuthMW()}
}

func _configMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publicsearchproductMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _basicMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publicsearchsuggestMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _getbasicconfigurationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publicgetproductcallinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categoryMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _getknowledgeconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publicgetproductcategorylistMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _updateknowledgeconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publicgetmarketpluginconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}
func _modelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletemodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmodellistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _knowledge0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _savebasicconfigurationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _retrieveconversationapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _retrievechatopenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chat0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _message0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listchatmessageapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _open_apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _knowledge1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _document0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdocumentopenapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdocumentopenapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedocumentopenapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _datasetsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdatasetopenapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dataset_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedatasetopenapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listphotodocumentopenapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdocumentprogressopenapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedatasetopenapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdatasetopenapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauth0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pluginoauthconfirmMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pluginoauthinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _plugin_oauthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _plugin_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pluginoauthauthorizationcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}
